[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "openpyxl",
    "fhir.resources",
    "pydantic",
    "validators",
    "odfpy"
]
build-backend = "setuptools.build_meta"