PROCESSES = [
        "triage",
        "emergency-care",
        "registration",
        "history-and-physical",
        "local-urgent-care",
        "acute-tertiary-care",
        "diagnostic-testing",
        "determine-diagnosis",
        "provide-counseling",
        "dispense-medications",
        "monitor-and-follow-up-of-patient",
        "alerts-reminders-education",
        "discharge-referral-of-patient",
        "charge-for-service",
        "record-and-report",
    ]