"""
FHIRStrategy: standard FHIR SDC output strategy for TRICC.

Generates:
- FHIR Questionnaire (one per process, with SDC extensions)
- CQL Libraries (helper + per-resource)
- FHIR StructureMap / FLM (data extraction)
- FHIR ValueSets (from TRICC CodeSystems)
- FHIR Binary (images)
- FSH files (via fsh_serializer)

This is the reusable FHIR base layer. openSRP/fhircore-specific resources
(Composition, PlanDefinition) are added by
``OpenSRPStrategy`` which inherits from this class.
"""

from __future__ import annotations

import base64
import datetime
import json
import logging
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from tricc_oo.converters.fhir.concept_mapper import get_fhir_resource
from tricc_oo.converters.fhir.structuremap import (
    apply_questionnaire_item_to_rule,
    build_extraction_rule,
    build_extraction_structuremap,
)
from tricc_oo.converters.fhir.ids import (
    fhir_resource_id,
    is_valid_fhir_id,
    readable_resource_filename,
    to_fhir_id,
)
from tricc_oo.converters.fhir.populate_helper import (
    cql_helper_populate_block,
    resolve_populate_reference,
)
from tricc_oo.converters.fhir.repeat_helper import (
    build_questionnaire_repeat_extension,
    cql_helper_repeat_block,
    get_observation_cql_accessor,
    get_observation_cql_accessor_for_node,
    should_emit_repeat_metadata,
)
from tricc_oo.converters.fhir.questionnaire_item_mapper import (
    CALCULATE_NODE_TYPES,
    SDC_EXT_CALCULATED_EXPR,
    SDC_EXT_ENABLE_WHEN_EXPR,
    SDC_EXT_HIDDEN,
    SDC_EXT_INITIAL_EXPR,
    build_answer_options_toggle_expression,
    build_enable_when_expression,
    build_hidden_extension,
    build_initial_expression,
    build_initial_expression_cql,
    build_calculated_expression_fhirpath,
    build_item_answer_media_extension,
    build_item_media_extension,
    get_display_type_extensions,
    get_fhir_item_type,
    image_content_type,
    is_hidden,
    is_repeating,
    item_allows_initial,
    should_skip,
    strip_illegal_initials,
)
from tricc_oo.converters.tricc_to_xls_form import get_export_name
from tricc_oo.converters.datadictionnary import lookup_codesystems_code
from tricc_oo.models.base import (
    RETURNS_BOOLEAN,
    TriccNodeType,
    TriccOperation,
    TriccOperator,
    TriccReference,
    TriccStatic,
    get_repeat,
)
from tricc_oo.models.tricc import (
    TriccNodeBaseModel,
    TriccNodeCalculateBase,
    TriccNodeInputModel,
    TriccNodeSelect,
    TriccNodeSelectOption,
    TriccNodeSelectYesNo,
    TriccNodeDisplayModel,
)
from tricc_oo.models.calculate import TriccNodeDisplayCalculateBase, TriccNodeInput, TriccNodePopulate
from tricc_oo.strategies.output.base_output_strategy import BaseOutPutStrategy
from tricc_oo.strategies.registry import register_output_strategy
from tricc_oo.visitors.tricc import get_node_expressions, get_process
logger = logging.getLogger("default")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DEFAULT_BASE_URL = "https://fhir.tricc.io"
FHIR_VERSION = "4.0.1"
QUESTIONNAIRE_PROFILE = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire"
LIBRARY_PROFILE = "http://hl7.org/fhir/StructureDefinition/Library"
STRUCTUREMAP_PROFILE = "http://hl7.org/fhir/StructureDefinition/StructureMap"
VALUESET_PROFILE = "http://hl7.org/fhir/StructureDefinition/ValueSet"
CODESYSTEM_PROFILE = "http://hl7.org/fhir/StructureDefinition/CodeSystem"

# List-context operators that work on collections without needing .first().value
LIST_CONTEXT_OPERATORS = {"contains", "selected", "has_qualifier", "count"}

# Hidden-item labels generated by graph rewiring (not author-facing copy).
_INTERNAL_ITEM_LABEL_PREFIXES = ("path:", "contains:", "save:")

# CQL helper library template (based on pyfhirsdc/core_fhir/cql/pyfhirsdc.cql patterns)
# Library names are quoted so FHIR-safe ids with hyphens are valid CQL identifiers.
CQL_HELPER_TEMPLATE = """\
library "{library_id}" version '1.0.0'

using FHIR version '{fhir_version}'

include FHIRHelpers version '{fhir_version}' called FHIRHelpers

// Current-visit Encounter id, passed in by the client at $populate time (null on a
// visit's first process — nothing recorded yet this encounter, which is expected).
// See feature/20260812-intervention-order-and-dedup.md.
parameter encounterid String default null

context Patient

// ── Observation helpers (repeat-aware, current-encounter-scoped) ─────────────

{repeat_helpers}

// ── Populate context helpers ─────────────────────────────────────────────────

{populate_helpers}

// ── Condition helpers ─────────────────────────────────────────────────────────

define function HasCondition(code String):
  exists(
    [Condition: Code code from "http://snomed.info/sct"] C
      where C.clinicalStatus ~ "active"
  )

// ── Age helpers ───────────────────────────────────────────────────────────────

define AgeInDays:
  duration in days between Patient.birthDate and Today()

define AgeInMonths:
  duration in months between Patient.birthDate and Today()

define AgeInYears:
  AgeInYears()
"""

# CQL child library template (per Questionnaire / PlanDefinition)
CQL_CHILD_TEMPLATE = """\
library "{library_id}" version '1.0.0'

using FHIR version '{fhir_version}'

include FHIRHelpers version '{fhir_version}' called FHIRHelpers
include "{helper_library_id}" version '1.0.0' called Helper

context Patient

"""


@register_output_strategy("FHIRStrategy")
class FHIRStrategy(BaseOutPutStrategy):
    """Standard FHIR SDC output strategy.

    Generates Questionnaire, Library+CQL, StructureMap/FLM, ValueSet, Binary,
    and FSH files from a TRICC project graph.

    Attributes:
        processes: List of process names to handle (default ``["main"]``).
        base_url: Canonical base URL for generated resources.
        questionnaires: Dict mapping process name → Questionnaire resource dict.
        cql_defines: Dict mapping process name → list of CQL define strings.
        structuremaps: Dict mapping process name → StructureMap resource dict.
        valuesets: Dict mapping list_name → ValueSet resource dict.
        binaries: List of Binary resource dicts (images).
    """

    processes = ["main"]
    project = None
    output_path = None

    def __init__(self, project, output_path: str, base_url: str = DEFAULT_BASE_URL, use_value_sets: bool = False):
        """Initialise the FHIRStrategy.

        Args:
            project: The TRICC project object.
            output_path: Directory path for output files.
            base_url: Canonical base URL for FHIR resources.
            use_value_sets: If True, generate external ValueSets and reference them via answerValueSet.
                            If False (default), hardcode options directly in the Questionnaire as answerOption
                            (easier for standalone testing).
        """
        super().__init__(project, output_path)
        self.base_url = (base_url or "https://fhir.tricc").rstrip("/")
        self.use_value_sets = use_value_sets
        self.questionnaires: Dict[str, dict] = {}
        self.cql_defines: Dict[str, List[str]] = {}
        self.structuremaps: Dict[str, dict] = {}
        self.extraction_maps: Dict[str, dict] = {}
        self.extraction_rules: Dict[str, list] = {}
        self.valuesets: Dict[str, dict] = {}
        self.binaries: List[dict] = []
        self._image_binary_ids: Dict[str, str] = {}
        self._project_image_index: Optional[Dict[str, str]] = None
        self._form_id: Optional[str] = None
        self.cql_libraries: Dict[str, str] = {}
        self.libraries: Dict[str, dict] = {}   # Phase 2: actual FHIR Library resources
        self.fml_mappings: Dict[str, str] = {}
        # Simple stack for building nested Questionnaire items (groups/activities)
        self._group_stack: list[tuple[str, dict]] = []

    def get_tricc_operation_expression(self, operation):
        # For CQL
        ref_expressions = []
        original_references = []
        if not hasattr(operation, "reference"):
            return self.get_tricc_operation_operand(operation)
        for r in operation.reference:
            if isinstance(r, list):
                r_expr = [
                    (
                        self.get_tricc_operation_expression(sr)
                        if isinstance(sr, TriccOperation)
                        else self.get_tricc_operation_operand(sr)
                    )
                    for sr in r
                ]
                original_references.append(r)
            elif isinstance(r, TriccOperation):
                r_expr = self.get_tricc_operation_expression(r)
                original_references.append(r)
            else:
                r_expr = self.get_tricc_operation_operand(r)
                original_references.append(r)
            if isinstance(r_expr, TriccReference):
                r_expr = self.get_tricc_operation_operand(r_expr)
            ref_expressions.append(r_expr)

        # build lower level
        if hasattr(self, f"tricc_operation_{operation.operator}"):
            callable = getattr(self, f"tricc_operation_{operation.operator}")
            return callable(ref_expressions, original_references)
        else:
            raise NotImplementedError(
                f"This type of operation '{operation.operator}' is not supported in this strategy"
            )

    def resolve_form_id(self, start_pages=None) -> str:
        """Resolve and cache the project form id (folder name; may contain ``_``).

        Args:
            start_pages: Optional start_pages dict; defaults to ``project.start_pages``.

        Returns:
            Raw form id string used for output paths.
        """
        if getattr(self, "_form_id", None):
            return self._form_id
        pages = start_pages if start_pages is not None else getattr(self.project, "start_pages", None)
        form_id = "fhir-form"
        if pages and "main" in pages:
            root = getattr(pages["main"], "root", None)
            form_id = (getattr(root, "form_id", None) if root else None) or form_id
        elif getattr(self.project, "form_id", None):
            form_id = self.project.form_id
        self._form_id = form_id
        return form_id

    @property
    def fhir_form_id(self) -> str:
        """FHIR-safe form id prefix for resource ids (no underscores)."""
        return to_fhir_id(getattr(self, "_form_id", None) or "fhir-form")

    def execute(self):
        """Run the full FHIR export pipeline."""
        version = datetime.datetime.now().strftime("%Y%m%d%H%M")
        logger.info(f"FHIRStrategy: build version {version}")
        # Resolve form id before library assembly so Library ids match PlanDefinitions
        self.resolve_form_id()
        if "main" in self.project.start_pages:
            self._group_stack = []  # reset nesting stack for a fresh run
            self.process_base(self.project.start_pages, pages=self.project.pages, version=version)
        else:
            logger.critical("Main process required")
            return

        logger.info("FHIRStrategy: generating relevance (enableWhenExpression)")
        self.process_relevance(self.project.start_pages, pages=self.project.pages)
        logger.info("FHIRStrategy: generating calculate (initialExpression / CQL)")
        self.process_calculate(self.project.start_pages, pages=self.project.pages)
        logger.info("FHIRStrategy: generating export (StructureMap)")
        self.process_export(self.project.start_pages, pages=self.project.pages)
        self._assemble_extraction_maps()

        # Build the actual CQL library texts from collected defines (Phase 2)
        # Must happen before export()
        self._assemble_cql_libraries()

        logger.info("FHIRStrategy: writing output files")
        self._sanitize_questionnaires()
        self.export(self.project.start_pages, version=version)
        logger.info("FHIRStrategy: validating")
        self.validate()

        # Final visibility log (helps developers immediately see the state of the FHIR export)
        logger.info(
            f"FHIRStrategy complete: {len(self.questionnaires)} questionnaire(s), "
            f"{len(self.cql_libraries)} CQL library file(s) written, "
            f"{len(self.fml_mappings)} FML mapping(s). "
            "See validate() output above for completeness warnings."
        )

    _YESNO_TRUE_MARKERS = {"true", "yes", "1", "y"}
    _YESNO_FALSE_MARKERS = {"false", "no", "0", "n"}

    def _boolean_choice_orientation_extension(self) -> Optional[dict]:
        """Rendering hint for visible boolean Questionnaire items.

        Generic FHIR SDC has none. ``OpenSRPStrategy`` overrides this to emit
        ``questionnaire-choiceOrientation=horizontal`` so Yes/No sit side by
        side. See ``feature/20260819-boolean-choice-orientation.md``.
        """
        return None

    @classmethod
    def _is_yesno_boolean_select(cls, node):
        """True if a select_one node's 2 options are a yes/no (true/false) pair,
        the case rendered as a native FHIR boolean item instead of a choice."""
        options = getattr(node, "options", None) or {}
        if len(options) != 2:
            return False
        markers = cls._YESNO_TRUE_MARKERS | cls._YESNO_FALSE_MARKERS
        opt_names = {str(o.name).lower() for o in options.values()}
        opt_codes = {str(getattr(o, "code", "")).lower() for o in options.values()}
        return bool(opt_names & markers or opt_codes & markers)

    @classmethod
    def _yesno_option_boolean_literal(cls, option):
        """FHIRPath boolean literal ('true'/'false', unquoted) for a select option
        belonging to a yes/no boolean-mapped select, or None if it isn't one."""
        marker = str(getattr(option, "code", None) or option.name).lower()
        if marker in cls._YESNO_TRUE_MARKERS:
            return "true"
        if marker in cls._YESNO_FALSE_MARKERS:
            return "false"
        return None

    def _get_project_image_content(self, file_name: str) -> Optional[str]:
        """Look up the base64 payload for a draw.io-embedded image by file name.

        ``project.images`` is populated once, at parse time, by
        ``xml_to_tricc.enrich_node``/``process_edges`` for every node/option
        that had an image-decorator box wired to it — it is the only place
        the actual image bytes live once parsing is done (the on-disk
        ``media-tmp/images/`` copy is not reachable from an output strategy,
        which only knows ``output_path``). Indexed lazily and cached since
        every question/option in a form is resolved against it.

        Args:
            file_name: Image file name as stored on ``node.image``/``opt.image``.

        Returns:
            The base64-encoded image payload, or ``None`` if not found.
        """
        if self._project_image_index is None:
            self._project_image_index = {
                entry["file_path"]: entry["image_content"]
                for entry in (getattr(self.project, "images", None) or [])
                if entry.get("file_path")
            }
        return self._project_image_index.get(file_name)

    def _register_image_binary(self, file_name: Optional[str]) -> Optional[Tuple[str, str]]:
        """Ensure a Binary resource exists for an image file, returning (id, contentType).

        Idempotent: the same file name always resolves to the same Binary id
        (deterministic UUID5, like every other resource id in this strategy),
        and is only appended to ``self.binaries`` once even if referenced from
        several questions/options.

        Args:
            file_name: Image file name as stored on ``node.image``/``opt.image``,
                or ``None``/empty if the node/option has no image.

        Returns:
            ``(binary_id, content_type)``, or ``None`` if there is no image,
            its type is unsupported, or its content could not be found.
        """
        if not file_name:
            return None
        content_type = image_content_type(file_name)
        if content_type is None:
            logger.warning("Image '%s' has no recognizable content type, skipping", file_name)
            return None
        if file_name in self._image_binary_ids:
            return self._image_binary_ids[file_name], content_type
        content = self._get_project_image_content(file_name)
        if content is None:
            logger.warning("Image '%s' referenced by a node but no content found, skipping", file_name)
            return None
        form_key = self.resolve_form_id()
        binary_id = fhir_resource_id(form_key, "Binary", file_name)
        self.binaries.append({
            "resourceType": "Binary",
            "id": binary_id,
            "contentType": content_type,
            "data": content,
        })
        self._image_binary_ids[file_name] = binary_id
        return binary_id, content_type

    def _build_item_media_extension(self, file_name: Optional[str]) -> Optional[dict]:
        """Build an itemMedia extension for a question's ``.image``, if any."""
        registered = self._register_image_binary(file_name)
        if registered is None:
            return None
        binary_id, content_type = registered
        return build_item_media_extension(binary_id, content_type)

    def _build_item_answer_media_extension(self, file_name: Optional[str]) -> Optional[dict]:
        """Build an itemAnswerMedia extension for an answer option's ``.image``, if any."""
        registered = self._register_image_binary(file_name)
        if registered is None:
            return None
        binary_id, content_type = registered
        return build_item_answer_media_extension(binary_id, content_type)

    def generate_base(self, node, **kwargs):
        """Build a Questionnaire.item from a TRICC node using the central mapper.

        Supports basic nesting: group-like nodes (activity_start, start, etc.)
        become "group" items and subsequent siblings are attached under them
        until a corresponding end node is seen.
        """
        tricc_type = getattr(node, 'tricc_type', None)
        if tricc_type is None:
            tricc_type = getattr(node, 'type', None) or str(getattr(node, '__class__', '')).lower()

        if should_skip(tricc_type) or isinstance(node, TriccNodeSelectOption):
            return True

        # Segment / process
        segment = self._node_segment(node)

        if segment not in self.questionnaires:
            form_key = self.resolve_form_id()
            q_id = fhir_resource_id(form_key, "Questionnaire", segment)
            q_name = to_fhir_id("questionnaire", segment)
            # "main" is the project's single root process (1 project = 1 Intervention):
            # its human title is the root node's authored label (same source other
            # output strategies use, e.g. xls_form.py/html_form.py), not the segment slug.
            q_title = q_name
            if segment == "main":
                main_page = self.project.start_pages.get("main")
                root_label = getattr(getattr(main_page, "root", None), "label", None)
                if root_label:
                    q_title = root_label
            self.questionnaires[segment] = {
                "resourceType": "Questionnaire",
                "id": q_id,
                "url": f"{self.base_url}/Questionnaire/{q_id}",
                "name": q_name,
                "title": q_title,
                "status": "draft",
                # openSRP QuestionnaireActivity requires subjectType (Patient for client forms)
                "subjectType": ["Patient"],
                "item": []
            }


        fhir_type = get_fhir_item_type(tricc_type)

        if fhir_type is None:
            # Purely structural/navigation node (activity_end, end, goto, link_in,
            # link_out, exclusive) — never rendered as a Questionnaire item. Still
            # pop the group stack for end/activity_end so nesting stays balanced.
            if tricc_type in ("end", "activity_end") and self._group_stack:
                self._group_stack.pop()
            return True

        # Special case requested: treat "yesno" style select_one as native boolean
        if fhir_type == "choice" and self._is_yesno_boolean_select(node):
            fhir_type = "boolean"

        if fhir_type == "string" and self._expression_returns_boolean(node):
            fhir_type = "boolean"

        label = getattr(node, 'label', None) or getattr(node, 'text', None) or ''
        # FIXME, does not work like this
        if isinstance(label, TriccOperation):
            # Display injection (CONCATENATE) or multi-lang: render via op expression / first locale
            label = self.get_tricc_operation_expression(label)
        hidden = fhir_type != "group" and (
            is_hidden(tricc_type) or isinstance(node, TriccNodeDisplayCalculateBase)
        )
        if hidden:
            label = self._sanitize_hidden_item_text(node, label)
        item = {
            "linkId": get_export_name(node),
            "text": label,
            "type": fhir_type,
        }

        if is_repeating(tricc_type):
            item["repeats"] = True

        extensions = get_display_type_extensions(
            getattr(node, 'display_type', None), tricc_type
        )
        # Groups must never carry questionnaire-hidden: SDC-aware renderers hide
        # a group's entire subtree along with it, masking all nested questions.
        if hidden:
            extensions.append(build_hidden_extension())
        media_extension = self._build_item_media_extension(getattr(node, "image", None))
        if media_extension:
            extensions.append(media_extension)
        if fhir_type == "boolean" and not hidden:
            orientation_ext = self._boolean_choice_orientation_extension()
            if orientation_ext:
                extensions.append(orientation_ext)
        if extensions:
            item["extension"] = extensions

        if should_emit_repeat_metadata(node):
            item.setdefault("extension", []).append(
                build_questionnaire_repeat_extension(get_repeat(node))
            )

        # Handle options (same logic as before)
        # Skip for boolean (e.g. select_yesno) — they use native true/false instead of choice options
        if fhir_type != "boolean" and hasattr(node, 'options') and node.options:
            if self.use_value_sets:
                pass  # Phase 3
            item["answerOption"] = []
            for opt in node.options.values():
                option_entry = {"valueCoding": self._answer_option_coding(opt)}
                answer_media_extension = self._build_item_answer_media_extension(
                    getattr(opt, "image", None)
                )
                if answer_media_extension:
                    option_entry["extension"] = [answer_media_extension]
                item["answerOption"].append(option_entry)

        # === Nesting logic (basic) ===
        is_group_starter = fhir_type == "group" and tricc_type in (
            "start", "activity_start", "page"
        )

        q = self.questionnaires[segment]
        target_list = q["item"]

        if self._group_stack:
            # We are inside a group — append to the top of the stack's "item" list
            _, parent_item = self._group_stack[-1]
            target_list = parent_item.setdefault("item", [])

        target_list.append(item)

        if is_group_starter:
            # Push this item onto the stack so children attach under it
            self._group_stack.append((segment, item))

        return True

    def generate_relevance(self, node, **kwargs):
        """Attach enableWhenExpression / option toggles (or hide the item)."""
        self._attach_option_toggles(node)

        relevance = self._effective_relevance(node)
        if relevance is None:
            return True

        segment = getattr(node, 'segment', None) or 'main'
        if segment not in self.questionnaires:
            return True

        fhirpath_expr = self.convert_expression_to_fhirpath(relevance)

        item = self._find_item_by_link_id(self.questionnaires[segment].get("item", []), get_export_name(node))
        if item is not None:
            if fhirpath_expr == 'false':
                item.setdefault("extension", []).append(build_hidden_extension())
            elif fhirpath_expr != 'true':
                item.setdefault("extension", []).append(
                    build_enable_when_expression(fhirpath_expr)
                )
        return True

    @staticmethod
    def _is_effective_relevance(rel) -> bool:
        if rel is None or rel is True or rel == "":
            return False
        if isinstance(rel, TriccStatic) and rel.value in (True, "true", ""):
            return False
        return isinstance(rel, (TriccOperation, TriccReference, TriccStatic, str)) or rel is False

    def _effective_relevance(self, node):
        """Relevance to emit on this Questionnaire item.

        Page / activity groups are authored as ``activity.relevance`` (XLSForm
        begin-group relevant). The activity_start node's own ``relevance`` is
        often ``true`` even when the page is gated (demo Page-2 = hungry OR bad_p).
        """
        tricc_type = getattr(node, "tricc_type", None)
        act = getattr(node, "activity", None)
        act_rel = getattr(act, "relevance", None) if act is not None else None
        if (
            isinstance(tricc_type, str)
            and tricc_type in ("start", "activity_start", "page")
            and self._is_effective_relevance(act_rel)
        ):
            return act_rel
        node_rel = getattr(node, "relevance", None)
        if self._is_effective_relevance(node_rel):
            return node_rel
        return None

    def _answer_option_coding(self, opt) -> dict:
        """Return the valueCoding dict used on both answerOption and toggle slices."""
        concept = lookup_codesystems_code(self.project.code_systems, opt.name)
        if concept:
            coding = {"code": concept.code, "display": concept.display}
            system = getattr(concept, "system", None)
            if system:
                coding["system"] = system
            return coding
        return {"code": opt.name, "display": getattr(opt, "label", opt.name)}

    def _option_relevance_is_always_on(self, relevance) -> bool:
        if relevance is None or relevance is True:
            return True
        if isinstance(relevance, TriccStatic) and relevance.value in (True, "true"):
            return True
        return False

    def _attach_option_toggles(self, node) -> None:
        """Emit answerOptionsToggleExpression for options that have relevance.

        Select options are not Questionnaire items, so their relevance is attached
        to the parent choice item (SDC context is Questionnaire.item).
        """
        options = getattr(node, "options", None)
        if not options or self._is_yesno_boolean_select(node):
            return

        segment = getattr(node, "segment", None) or "main"
        q = self.questionnaires.get(segment)
        if not q:
            return
        item = self._find_item_by_link_id(q.get("item", []), get_export_name(node))
        if item is None:
            return

        grouped = {}
        order = []
        for opt in options.values():
            relevance = getattr(opt, "relevance", None)
            if self._option_relevance_is_always_on(relevance):
                continue
            try:
                fhirpath_expr = self.convert_expression_to_fhirpath(relevance)
            except NotImplementedError as exc:
                logger.debug(
                    "Skipping option toggle for %s on %s: %s",
                    getattr(opt, "name", None),
                    get_export_name(node),
                    exc,
                )
                continue
            if fhirpath_expr == "true":
                continue
            if fhirpath_expr not in grouped:
                grouped[fhirpath_expr] = []
                order.append(fhirpath_expr)
            grouped[fhirpath_expr].append(self._answer_option_coding(opt))

        for fhirpath_expr in order:
            item.setdefault("extension", []).append(
                build_answer_options_toggle_expression(grouped[fhirpath_expr], fhirpath_expr)
            )

    @staticmethod
    def _find_item_by_link_id(items, link_id):
        """Recursively search a Questionnaire item list (including group children)
        for an item with the given linkId."""
        for item in items:
            if item.get("linkId") == link_id:
                return item
            child = FHIRStrategy._find_item_by_link_id(item.get("item", []), link_id)
            if child is not None:
                return child
        return None

    @staticmethod
    def _collect_calculate_references(expression):
        """Flatten a calculate node's expression_reference/reference into the leaf
        node/TriccReference objects it depends on (skips plain literals)."""
        if isinstance(expression, TriccOperation):
            return list(expression.get_references())
        if isinstance(expression, list):
            refs = []
            for e in expression:
                refs.extend(FHIRStrategy._collect_calculate_references(e))
            return refs
        if isinstance(expression, TriccReference):
            return [expression]
        if expression is not None and issubclass(expression.__class__, TriccNodeBaseModel):
            return [expression]
        return []

    def generate_calculate(self, node, **kwargs):
        """Record the calculate node's value source and attach the matching SDC
        extension: calculatedExpression (FHIRPath) when it can be recomputed live
        from other items already in this Questionnaire, otherwise initialExpression
        (CQL, evaluated once at $populate) when it depends on data outside the form
        (e.g. observation history reachable only through the CQL Helper library)."""
        tricc_type = getattr(node, "tricc_type", None)
        if tricc_type not in CALCULATE_NODE_TYPES and not isinstance(node, TriccNodePopulate):
            # Not a value-producing calculate node (e.g. a group/navigation node
            # such as activity_start/activity_end/link_out) — nothing to attach.
            return True

        segment = getattr(node, "segment", "main")
        q = self.questionnaires.get(segment)
        if not q:
            return True

        link_id = get_export_name(node)
        calc_name = f"Calc_{link_id}"

        if isinstance(node, TriccNodePopulate):
            cql_expr = resolve_populate_reference(node, qualified=True)
            if segment not in self.cql_defines:
                self.cql_defines[segment] = []
            self.cql_defines[segment].append(f"define {calc_name}: {cql_expr}")
            item = self._find_item_by_link_id(q.get("item", []), link_id)
            if item is not None and item_allows_initial(item):
                item.setdefault("extension", []).append(build_initial_expression(calc_name))
            return True

        expression = getattr(node, "expression_reference", None) or getattr(node, "reference", None)
        if not expression:
            # Synthetic nodes (e.g. the "path" bridges GoTo/Rhombus branches are
            # rewired through, see inject_bridge_path) never get an
            # expression_reference/reference of their own. Derive their value the
            # same way xls_form/dhis2/openmrs already do via the shared visitor,
            # instead of silently skipping the calculatedExpression/initialExpression.
            if (
                getattr(node, "expression", None) is None
                and issubclass(node.__class__, TriccNodeCalculateBase)
            ):
                node.expression = get_node_expressions(
                    node, kwargs.get("processed_nodes"), process=kwargs.get("process")
                )
            expression = getattr(node, "expression", None)
        if not expression:
            return True

        # calculatedExpression is FHIRPath-only; it can only reach values already
        # answered/computed in *this* Questionnaire (%resource.repeat(item).where(linkId=...)).
        # If at least one reference is captured here, prefer the live-recalculating
        # calculatedExpression; otherwise fall back to a one-time CQL initialExpression.
        references = self._collect_calculate_references(expression)
        captured_in_questionnaire = any(
            not isinstance(ref, TriccReference)
            and self._find_item_by_link_id(q.get("item", []), get_export_name(ref)) is not None
            for ref in references
        )

        if captured_in_questionnaire:
            try:
                fhirpath_expr = self.convert_expression_to_fhirpath(expression)
            except NotImplementedError as e:
                logger.debug(f"Falling back to CQL for {link_id}: {e}")
                fhirpath_expr = None
        else:
            fhirpath_expr = None

        item = self._find_item_by_link_id(q.get("item", []), link_id)

        if fhirpath_expr:
            if item is not None:
                if item.get("type") == "string" and self._expression_returns_boolean(expression):
                    item["type"] = "boolean"
                item.setdefault("extension", []).append(build_calculated_expression_fhirpath(fhirpath_expr))
            return True

        # No in-form reference (or the expression isn't FHIRPath-representable):
        # compute once via CQL and expose it through initialExpression instead.
        try:
            cql_expr = self.convert_expression_to_cql(expression)
        except Exception as e:
            logger.debug(f"Could not convert calculate expression for {link_id}: {e}")
            return True

        if segment not in self.cql_defines:
            self.cql_defines[segment] = []
        self.cql_defines[segment].append(f"define {calc_name}: {cql_expr}")

        if item is not None and item_allows_initial(item):
            item.setdefault("extension", []).append(build_initial_expression(calc_name))

        return True

    def _node_segment(self, node) -> str:
        """Return the Questionnaire / process key for a node."""
        segment = getattr(node, "segment", None) or getattr(node, "process", None) or "main"
        try:
            proc = get_process(node)
            if proc:
                return proc
        except Exception:
            pass
        return segment

    def _segment_for_item(self, node, link_id: str) -> str:
        """Return the Questionnaire that already contains ``link_id``.

        Group nesting can place an item under a parent in ``main`` even when
        ``get_process(node)`` reports another cpg-common-process (e.g.
        ``registration``). Extraction must follow the Questionnaire, not the
        graph process, or prune-empty will drop the rules.
        """
        if link_id:
            for process, q in (self.questionnaires or {}).items():
                if self._find_item_by_link_id(q.get("item", []), link_id) is not None:
                    return process
        return self._node_segment(node)

    def generate_export(self, node, **kwargs):
        """Collect conceptType-driven extraction rules and attach dedup expressions."""
        from tricc_oo.converters.fhir.concept_mapper import resolve_concept_type

        concept_type = resolve_concept_type(
            node, getattr(self.project, "code_systems", None)
        )
        fhir_resource, _, _ = get_fhir_resource(concept_type, getattr(node, "tricc_type", None))
        try:
            link_id = get_export_name(node)
        except Exception:
            link_id = getattr(node, "name", None) or ""

        rule = build_extraction_rule(
            node,
            codesystems=getattr(self.project, "code_systems", None),
            default_code_system=f"{self.base_url}/CodeSystem/tricc",
        )
        if rule is not None:
            q_item = self._find_item_anywhere(rule.link_id)
            apply_questionnaire_item_to_rule(rule, q_item)
            segment = self._segment_for_item(node, rule.link_id)
            self.extraction_rules.setdefault(segment, []).append(rule)
            # Dedup only on items that are actually extracted as Observation/Condition.
            # Notes/groups default to Observation in get_fhir_resource() and must not
            # receive initialExpression (SDC + openSRP $populate).
            if link_id:
                self._attach_dedup_initial_expression(node, fhir_resource, link_id)
        return True

    def _assemble_extraction_maps(self, version: str = "1.0.0") -> None:
        """Build one QuestionnaireResponse → Bundle StructureMap per process."""
        form_key = self.resolve_form_id()
        processes = set(self.questionnaires or {}) | set(self.extraction_rules or {})
        for process in processes:
            rules = list(self.extraction_rules.get(process) or [])
            sm = build_extraction_structuremap(
                rules=rules,
                form_id=form_key,
                process=process,
                base_url=self.base_url,
                version=version,
            )
            self.extraction_maps[process] = sm
            self.fml_mappings[process] = sm.get("_fml") or ""

    def _attach_dedup_initial_expression(self, node, fhir_resource: str, link_id: str) -> None:
        """Auto-attach a dedup ``initialExpression`` for Observation/Condition-typed items.

        Pulls the same code from the current encounter (if already recorded by an
        earlier process in this visit) so the item pre-fills instead of re-asking the
        same question twice. Skipped when the item already has an author-authored
        populate/calculate `initialExpression`/`calculatedExpression` — that takes
        precedence. MedicationRequest/MedicationDispense are out of scope (no node
        type produces them yet — see
        feature/20260812-medication-request-dispense-node.md). See
        feature/20260812-intervention-order-and-dedup.md.
        """
        if fhir_resource not in ("Observation", "Condition"):
            return
        segment = self._segment_for_item(node, link_id)
        q = self.questionnaires.get(segment)
        if not q:
            return
        item = self._find_item_by_link_id(q.get("item", []), link_id)
        if item is None:
            return
        # SDC: initialExpression is illegal on group/display (openSRP ResourceMapper
        # throws IllegalStateException at $populate).
        if not item_allows_initial(item):
            return
        existing = item.get("extension") or []
        if any(e.get("url") in (SDC_EXT_INITIAL_EXPR, SDC_EXT_CALCULATED_EXPR) for e in existing):
            return  # author-authored populate/calculate already covers this item

        if fhir_resource == "Observation":
            # Repeat-aware: a repeat-slot-N item must dedup against slot N specifically,
            # not just any past Observation with this code (see get_observation_cql_accessor).
            cql_expr = get_observation_cql_accessor_for_node(node)
        else:
            code = (getattr(node, "name", None) or link_id).replace("'", "\\'")
            cql_expr = f"Helper.GetConditionValue('{code}')"

        calc_name = f"Dedup_{link_id}"
        if segment not in self.cql_defines:
            self.cql_defines[segment] = []
        self.cql_defines[segment].append(f"define {calc_name}: {cql_expr}")
        item.setdefault("extension", []).append(build_initial_expression(calc_name))

    def _sanitize_questionnaires(self) -> None:
        """Strip SDC-illegal ``initial`` / ``initialExpression`` before write.

        Last-line defence: group and display items must never carry them, or
        openSRP FHIR Data Capture refuses to render the Questionnaire.
        """
        for segment, q in (self.questionnaires or {}).items():
            removed = strip_illegal_initials(q.get("item"))
            if removed:
                logger.warning(
                    "FHIRStrategy: stripped illegal initial/initialExpression from "
                    "%s group/display item(s) in Questionnaire '%s'",
                    removed,
                    segment,
                )

    def export(self, start_pages, version):
        form_id = self.resolve_form_id(start_pages)
        base_path = os.path.join(self.output_path, form_id)
        if not os.path.exists(base_path):
            os.makedirs(base_path)

        # Export Questionnaires — readable filenames; REST id is JSON ``id`` (UUID)
        q_dir = os.path.join(base_path, "questionnaire")
        os.makedirs(q_dir, exist_ok=True)
        for segment, q in self.questionnaires.items():
            file_name = readable_resource_filename(
                q, prefix="Questionnaire", fallback=segment
            )
            path = os.path.join(q_dir, file_name)
            with open(path, "w", encoding="utf-8") as f:
                json.dump(q, f, indent=2, ensure_ascii=False)

        # Export CQL source + Library JSON resources (Phase 2)
        lib_dir = os.path.join(base_path, "library")
        os.makedirs(lib_dir, exist_ok=True)
        for key, cql in self.cql_libraries.items():
            lib = self.libraries.get(key) if self.libraries else None
            stem = to_fhir_id(
                (lib or {}).get("name") or key if isinstance(lib, dict) else key
            )
            # .cql source (useful for debugging)
            cql_path = os.path.join(lib_dir, f"{stem}.cql")
            with open(cql_path, "w", encoding="utf-8") as f:
                f.write(cql)

            # Corresponding FHIR Library JSON (filename from name; id is UUID)
            if isinstance(lib, dict):
                lib_path = os.path.join(
                    lib_dir,
                    readable_resource_filename(lib, prefix="Library", fallback=stem),
                )
                with open(lib_path, "w", encoding="utf-8") as f:
                    json.dump(lib, f, indent=2, ensure_ascii=False)

        # Export extraction StructureMaps (JSON + companion FML)
        if self.extraction_maps:
            sm_dir = os.path.join(base_path, "structure-map")
            os.makedirs(sm_dir, exist_ok=True)
            for process, sm in self.extraction_maps.items():
                payload = {k: v for k, v in sm.items() if not k.startswith("_")}
                file_name = readable_resource_filename(
                    sm, prefix="StructureMap", fallback=f"{process}-extract"
                )
                path = os.path.join(sm_dir, file_name)
                with open(path, "w", encoding="utf-8") as f:
                    json.dump(payload, f, indent=2, ensure_ascii=False)
                fml = sm.get("_fml")
                if fml:
                    map_stem = file_name[: -len(".json")] if file_name.endswith(".json") else file_name
                    with open(os.path.join(sm_dir, f"{map_stem}.map"), "w", encoding="utf-8") as f:
                        f.write(fml)

        logger.info(f"Exported FHIR resources to {base_path}")


    def get_tricc_operation_operand(self, r):
        if isinstance(r, TriccOperation):
            return self.get_tricc_operation_expression(r)
        elif isinstance(r, TriccReference):
            if isinstance(r.value, str):
                return get_observation_cql_accessor(r.value, 1)
            return get_export_name(r.value)
        elif isinstance(r, TriccStatic):
            if isinstance(r.value, str):
                value = f"'{r.value}'"
            else:
                value = str(r.value)
            if value == "True":
                return "true"
            elif value == "False":
                return "false"
            else:
                return value
        elif isinstance(r, bool):
            return 'true' if r else 'false'
        elif isinstance(r, str):
            return f"'{r}'"
        elif isinstance(r, (int, float)):
            return str(r)
        elif isinstance(r, TriccNodeSelectOption):
            return f"'{r.name}'"
        elif isinstance(r, TriccNodeInput):
            return get_observation_cql_accessor_for_node(r)
        elif isinstance(r, TriccNodePopulate):
            return resolve_populate_reference(r, qualified=True)
        elif issubclass(r.__class__, TriccNodeInputModel):
            return get_export_name(r)
        elif issubclass(r.__class__, TriccNodeBaseModel):
            return get_export_name(r)
        else:
            raise NotImplementedError(f"This type of node {r.__class__} is not supported within an operation")

    def convert_expression_to_cql(self, expression):
        if isinstance(expression, TriccOperation):
            return self.get_tricc_operation_expression(expression)
        else:
            return self.get_tricc_operation_operand(expression)

    def _assemble_cql_libraries(self):
        """Turn collected cql_defines into full CQL text + Library resources (Phase 2)."""
        if not self.cql_defines:
            return

        import base64

        form_id = self.resolve_form_id()
        fhir_form = self.fhir_form_id
        # CQL names stay human-readable; FHIR Library.id is a UUID (REST / openSRP style)
        # Dict keys use logical names so export filenames stay readable.
        helper_cql_name = to_fhir_id(fhir_form, "Helper")
        helper_id = fhir_resource_id(form_id, "Library", "Helper")
        helper_key = "Helper"

        # Build helper library (once)
        helper_cql = CQL_HELPER_TEMPLATE.format(
            library_id=helper_cql_name,
            fhir_version=FHIR_VERSION,
            repeat_helpers=cql_helper_repeat_block(FHIR_VERSION),
            populate_helpers=cql_helper_populate_block(),
        )
        self.cql_libraries[helper_key] = helper_cql

        # Create FHIR Library resource for helper
        self.libraries[helper_key] = self._make_library_resource(
            helper_id, helper_cql, form_id, name=helper_cql_name
        )

        # Build one child library per segment/process
        for segment, defines in self.cql_defines.items():
            cql_name = to_fhir_id(fhir_form, segment)
            lib_id = fhir_resource_id(form_id, "Library", segment)
            defines_block = "\n\n".join(defines)

            child_cql = CQL_CHILD_TEMPLATE.format(
                library_id=cql_name,
                fhir_version=FHIR_VERSION,
                helper_library_id=helper_cql_name,
            )
            child_cql += "\n\n" + defines_block + "\n"

            self.cql_libraries[segment] = child_cql

            # Create FHIR Library resource
            self.libraries[segment] = self._make_library_resource(
                lib_id, child_cql, form_id, name=cql_name
            )

    def _make_library_resource(
        self, lib_id: str, cql_text: str, form_id: str, name: Optional[str] = None
    ) -> dict:
        """Create a FHIR Library resource with embedded CQL.

        Args:
            lib_id: Server resource id (UUID preferred).
            cql_text: CQL source text.
            form_id: Human form id for titles.
            name: Optional human-readable ``name`` (CQL library token).
        """
        import base64

        # lib_id is already a UUID from fhir_resource_id; do not re-sanitize hyphens away
        resource_id = lib_id if is_valid_fhir_id(lib_id) else to_fhir_id(lib_id)
        lib_name = name or to_fhir_id(lib_id)
        encoded = base64.b64encode(cql_text.encode("utf-8")).decode("ascii")

        return {
            "resourceType": "Library",
            "id": resource_id,
            "url": f"{self.base_url}/Library/{resource_id}",
            "version": "1.0.0",
            "name": lib_name,
            "title": f"{form_id} - {lib_name} CQL Library",
            "status": "draft",
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/library-type",
                        "code": "logic-library",
                    }
                ]
            },
            "content": [
                {
                    "contentType": "text/cql",
                    "data": encoded,
                }
            ],
        }

    def convert_expression_to_fhirpath(self, expression):
        # For FHIRPath, similar to CQL but in FHIR context
        # For questionnaire, references to other questions
        if isinstance(expression, TriccOperation):
            return self.get_tricc_operation_expression_fhirpath(expression)
        else:
            return self.get_tricc_operation_operand_fhirpath(expression)

    def _wrap_operand_if_needed(self, r_expr, original_ref) -> str:
        """Wrap a single operand expression with .where($this.exists()).first()
        if the original reference is a Questionnaire answer collection.

        - TriccOperation references are *not* wrapped (the inner operation
          already handles its own scalar output).
        - List sub-references are wrapped element-by-element.
        - TriccReference / TriccNodeInputModel / TriccNodeBaseModel references
          produce answer collections and therefore need the wrapper.
        """
        if isinstance(original_ref, TriccOperation):
            # Inner operation already returns a scalar – do not double-wrap.
            return r_expr

        if isinstance(original_ref, list):
            # Each element in the list is an independent sub-reference.
            for o_r in original_ref:
                r_expr = self._wrap_operand_if_needed(r_expr, o_r)
            # Fallback: treat the whole list expression as a single item.
            return r_expr

        if self._should_wrap_first(original_ref):
            search = self.get_tricc_operation_operand_fhirpath(original_ref)
            replace = f"{search}.where($this.exists()){self._answer_value_suffix(original_ref)}"
            return r_expr.replace(search, replace)

        return r_expr

    def get_tricc_operation_expression_fhirpath(self, operation):
        ref_expressions = []
        original_references = []
        if not hasattr(operation, "reference"):
            return self.get_tricc_operation_operand_fhirpath(operation)
        for r in operation.reference:
            if isinstance(r, list):
                r_expr = [
                    (
                        self.get_tricc_operation_expression_fhirpath(sr)
                        if isinstance(sr, TriccOperation)
                        else self.get_tricc_operation_operand_fhirpath(sr)
                    )
                    for sr in r
                ]
                original_references.append(r)
            elif isinstance(r, TriccOperation):
                r_expr = self.get_tricc_operation_expression_fhirpath(r)
                original_references.append(r)
            else:
                r_expr = self.get_tricc_operation_operand_fhirpath(r)
                original_references.append(r)
            if isinstance(r_expr, TriccReference):
                r_expr = self.get_tricc_operation_operand_fhirpath(r_expr)
            # ───────────────────────────────────────────────────────────────
            ref_expressions.append(r_expr)

        if hasattr(self, f"tricc_operation_fhirpath_{operation.operator}"):
            callable = getattr(self, f"tricc_operation_fhirpath_{operation.operator}")
            return callable(ref_expressions, original_references)
        else:
            # Fallback to CQL operations
            if hasattr(self, f"tricc_operation_{operation.operator}"):
                callable = getattr(self, f"tricc_operation_{operation.operator}")
                return callable(ref_expressions, original_references)
            else:
                raise NotImplementedError(
                    f"This type of operation '{operation.operator}' is not supported"
                )

    def get_tricc_operation_operand_fhirpath(self, r):
        if isinstance(r, TriccOperation):
            return self.get_tricc_operation_expression_fhirpath(r)
        elif isinstance(r, TriccReference):
            # Nested groups are the common case; repeat(item) walks descendants.
            return self._fhirpath_answer(get_export_name(r.value))
        elif isinstance(r, TriccStatic):
            if isinstance(r.value, str):
                value = f"'{r.value}'"
            else:
                value = str(r.value)
            if value == "True":
                return "true"
            elif value == "False":
                return "false"
            else:
                return value
        elif isinstance(r, bool):
            return 'true' if r else 'false'
        elif isinstance(r, str):
            return f"'{r}'"
        elif isinstance(r, (int, float)):
            return str(r)
        elif isinstance(r, TriccNodeSelectOption):
            if self._is_yesno_boolean_select(getattr(r, "select", None)):
                literal = self._yesno_option_boolean_literal(r)
                if literal is not None:
                    return literal
            return f"'{r.name}'"
        elif issubclass(r.__class__, TriccNodeInputModel):
            return self._fhirpath_answer(get_export_name(r))
        elif issubclass(r.__class__, TriccNodeBaseModel):
            return self._fhirpath_answer(get_export_name(r))
        else:
            raise NotImplementedError(f"This type of node {r.__class__} is not supported within an operation")

    # FHIRPath operations, same as CQL for now
    def tricc_operation_fhirpath_and(self, ref_expressions, original_references=None):
        return " and ".join(ref_expressions)

    def tricc_operation_fhirpath_or(self, ref_expressions, original_references=None):
        return " or ".join(ref_expressions)

    def tricc_operation_fhirpath_not(self, ref_expressions, original_references=None):
        # FHIRPath has no unary `not` operator. `not` is a 0-arg function; HAPI
        # rejects `not (expr)` with "The function \"not\" requires 0 parameters".
        return f"({ref_expressions[0]}).not()"

    def tricc_operation_fhirpath_plus(self, ref_expressions, original_references=None):
        return " + ".join(ref_expressions)

    def tricc_operation_fhirpath_minus(self, ref_expressions, original_references=None):
        if len(ref_expressions) > 1:
            return " - ".join(ref_expressions)
        return f"-{ref_expressions[0]}"

    def tricc_operation_fhirpath_more(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} > {ref_expressions[1]}"

    def tricc_operation_fhirpath_less(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} < {ref_expressions[1]}"

    # Operation methods for CQL
    def tricc_operation_equal(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} = {ref_expressions[1]}"

    def tricc_operation_not_equal(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} != {ref_expressions[1]}"

    def tricc_operation_and(self, ref_expressions, original_references=None):
        return " and ".join(ref_expressions)

    def tricc_operation_or(self, ref_expressions, original_references=None):
        return " or ".join(ref_expressions)

    def tricc_operation_not(self, ref_expressions, original_references=None):
        return f"not {ref_expressions[0]}"

    def tricc_operation_plus(self, ref_expressions, original_references=None):
        return " + ".join(ref_expressions)

    def tricc_operation_minus(self, ref_expressions, original_references=None):
        if len(ref_expressions) > 1:
            return " - ".join(ref_expressions)
        return f"-{ref_expressions[0]}"

    def tricc_operation_more(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} > {ref_expressions[1]}"

    def tricc_operation_less(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} < {ref_expressions[1]}"

    def tricc_operation_more_or_equal(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} >= {ref_expressions[1]}"

    def tricc_operation_less_or_equal(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]} <= {ref_expressions[1]}"

    # ============================================================
    # HELPER: Flexible .first() for FHIRPath only (per operation level)
    # ============================================================
    def _should_wrap_first(self, original_ref) -> bool:
        """Return True if the original reference is known to produce a collection
        that needs .first() in FHIRPath."""
        if original_ref is None:
            return False
        # TriccReference subclasses TriccStatic, so it must be checked first —
        # otherwise it would be caught (and excluded) by the TriccStatic branch below.
        if isinstance(original_ref, TriccReference):
            return True
        if isinstance(original_ref, (TriccStatic, str, TriccOperation, TriccNodeSelectOption)):
            return False
        if isinstance(original_ref, (TriccNodeInputModel, TriccNodeBaseModel)):
            return True
        return False

    @staticmethod
    def _fhirpath_answer(link_id: str) -> str:
        """QuestionnaireResponse.answer collection for ``link_id``, including nested groups."""
        return f"%resource.repeat(item).where(linkId='{link_id}').answer"

    @staticmethod
    def _sanitize_hidden_item_text(node, label) -> str:
        """Drop graph-routing labels from hidden items; keep author-facing copy."""
        text = "" if label is None else str(label)
        stripped = text.strip()
        if not stripped or stripped.lower().startswith(_INTERNAL_ITEM_LABEL_PREFIXES):
            return getattr(node, "name", None) or ""
        return text

    def _expression_returns_boolean(self, node_or_expression) -> bool:
        """True when a calculate node's value is a boolean operation."""
        expr = node_or_expression
        if not isinstance(expr, TriccOperation):
            expr = getattr(node_or_expression, "expression_reference", None) or getattr(
                node_or_expression, "expression", None
            )
        if isinstance(expr, TriccOperation):
            return self._operation_returns_boolean(expr)
        return False

    def _find_item_anywhere(self, link_id: str):
        """Search every Questionnaire for ``link_id`` (nested groups included)."""
        if not link_id:
            return None
        for q in (self.questionnaires or {}).values():
            item = self._find_item_by_link_id(q.get("item", []), link_id)
            if item is not None:
                return item
        return None

    def _is_boolean_item_reference(self, original_ref) -> bool:
        """True when ``original_ref`` is a native boolean Questionnaire item."""
        if original_ref is None:
            return False
        if isinstance(original_ref, TriccNodeSelectYesNo):
            return True
        if isinstance(original_ref, TriccNodeSelect) and self._is_yesno_boolean_select(original_ref):
            return True
        link_id = None
        if isinstance(original_ref, TriccReference):
            try:
                link_id = get_export_name(original_ref.value)
            except Exception:
                link_id = str(original_ref.value)
        elif issubclass(getattr(original_ref, "__class__", object), TriccNodeBaseModel):
            try:
                link_id = get_export_name(original_ref)
            except Exception:
                link_id = getattr(original_ref, "name", None)
        item = self._find_item_anywhere(link_id) if link_id else None
        return bool(item and item.get("type") == "boolean")

    def _is_choice_reference(self, original_ref) -> bool:
        """True when ``original_ref`` is a choice / open-choice item (not yes/no boolean)."""
        if original_ref is None or self._is_boolean_item_reference(original_ref):
            return False
        if isinstance(original_ref, TriccNodeSelect):
            return True
        link_id = None
        if isinstance(original_ref, TriccReference):
            try:
                link_id = get_export_name(original_ref.value)
            except Exception:
                link_id = str(original_ref.value)
        elif issubclass(getattr(original_ref, "__class__", object), TriccNodeBaseModel):
            try:
                link_id = get_export_name(original_ref)
            except Exception:
                link_id = getattr(original_ref, "name", None)
        item = self._find_item_anywhere(link_id) if link_id else None
        if item is not None:
            return item.get("type") in ("choice", "open-choice")
        # Unknown references stay on .value for scalar wrap; SELECTED/CONTAINS
        # still treat unresolved operands as coded membership (see those emitters).
        return False

    def _is_string_item_reference(self, original_ref) -> bool:
        """True when CONTAINS should stay a substring test rather than code membership."""
        if original_ref is None:
            return False
        tricc_type = getattr(original_ref, "tricc_type", None)
        if tricc_type == TriccNodeType.text:
            return True
        link_id = None
        if isinstance(original_ref, TriccReference):
            try:
                link_id = get_export_name(original_ref.value)
            except Exception:
                link_id = str(original_ref.value)
        elif issubclass(getattr(original_ref, "__class__", object), TriccNodeBaseModel):
            try:
                link_id = get_export_name(original_ref)
            except Exception:
                link_id = getattr(original_ref, "name", None)
        item = self._find_item_anywhere(link_id) if link_id else None
        return bool(item and item.get("type") in ("string", "text"))

    def _answer_value_suffix(self, original_ref) -> str:
        """FHIRPath suffix that reads the scalar answer value for ``original_ref``."""
        if self._is_choice_reference(original_ref):
            return ".value.code"
        return ".value"

    def _choice_answer_collection(self, answer_expr: str) -> str:
        """Strip any ``.value[.Coding].code`` suffix so we have the ``…answer`` collection."""
        base = answer_expr or ""
        for suffix in (".valueCoding.code", ".value.code"):
            if base.endswith(suffix):
                return base[: -len(suffix)]
        return base

    def _choice_membership_expr(self, answer_expr: str, code_expr: str) -> str:
        """True when a choice answer includes ``code_expr``.

        HAPI FHIRPath on ``QuestionnaireResponse.item.answer`` exposes polymorphic
        ``value``, not ``valueCoding``. ``'code' in …answer.valueCoding.code`` is
        always empty/false. ``answer.where(value.code = 'x').exists()`` matches
        a selected option.
        """
        answers = self._choice_answer_collection(answer_expr)
        return f"{answers}.where(value.code = {code_expr}).exists()"

    def _choice_codes_expr(self, answer_expr: str) -> str:
        """Collection of choice codes from an ``…answer`` FHIRPath."""
        answers = self._choice_answer_collection(answer_expr)
        if answers.endswith(".answer"):
            return f"{answers}.value.code"
        return f"{answer_expr}.value.code" if answer_expr else answer_expr

    def _operation_returns_boolean(self, expr) -> bool:
        """True when ``expr`` is a boolean TriccOperation (walks parenthesis)."""
        if isinstance(expr, TriccOperation):
            if expr.operator == TriccOperator.PARENTHESIS and expr.reference:
                return self._operation_returns_boolean(expr.reference[0])
            return expr.operator in RETURNS_BOOLEAN or expr.operator in (
                TriccOperator.ISNULL,
                TriccOperator.CAST_BOOLEAN,
            )
        return False

    # ============================================================
    # BOOLEAN / LOGICAL OPERATORS
    # ============================================================
    def tricc_operation_istrue(self, ref_expressions, original_references=None):
        # CQL: treat as identity or explicit comparison
        return f"({ref_expressions[0]} is true)"

    def tricc_operation_isnottrue(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is not true)"

    def tricc_operation_isfalse(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is false)"

    def tricc_operation_isnotfalse(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is not false)"

    def tricc_operation_isnull(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is null)"

    def tricc_operation_isnotnull(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is not null)"

    def tricc_operation_selected(self, ref_expressions, original_references=None):
        # ref[0] is the select field, remaining refs are the option values

        return f"({ref_expressions[1]} in {ref_expressions[0]})"

    def tricc_operation_between(self, ref_expressions, original_references=None):
        # ref[0] between low and high
        if len(ref_expressions) >= 3:
            return f"({ref_expressions[0]} between {ref_expressions[1]} and {ref_expressions[2]})"
        return ref_expressions[0]

    def tricc_operation_contains(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} contains {ref_expressions[1]})"

    def tricc_operation_exists(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is not null)"

    def tricc_operation_notexists(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} is null)"

    def tricc_operation_has_qualifier(self, ref_expressions, original_references=None):
        # Not implemented for now (CDSS specific)
        raise NotImplementedError("HAS_QUALIFIER is not supported yet")

    # ============================================================
    # ARITHMETIC OPERATORS
    # ============================================================
    def tricc_operation_divided(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} / {ref_expressions[1]})"

    def tricc_operation_multiplied(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} * {ref_expressions[1]})"

    def tricc_operation_modulo(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]} mod {ref_expressions[1]})"

    def tricc_operation_round(self, ref_expressions, original_references=None):
        return f"Round({ref_expressions[0]})"

    def tricc_operation_abs(self, ref_expressions, original_references=None):
        return f"Abs({ref_expressions[0]})"

    def tricc_operation_min(self, ref_expressions, original_references=None):
        # MIN of a list -> use Min() aggregate
        items = ", ".join(ref_expressions)
        return f"Min({{{items}}})"

    def tricc_operation_max(self, ref_expressions, original_references=None):
        items = ", ".join(ref_expressions)
        return f"Max({{{items}}})"

    def tricc_operation_sum(self, ref_expressions, original_references=None):
        items = ", ".join(ref_expressions)
        return f"Sum({{{items}}})"

    def tricc_operation_count(self, ref_expressions, original_references=None):
        items = ", ".join(ref_expressions)
        return f"Count({{{items}}})"

    # ============================================================
    # CASTING & CONVERSION
    # ============================================================
    def tricc_operation_cast_number(self, ref_expressions, original_references=None):
        return f"ToDecimal({ref_expressions[0]})"

    def tricc_operation_cast_integer(self, ref_expressions, original_references=None):
        return f"ToInteger({ref_expressions[0]})"

    def tricc_operation_cast_date(self, ref_expressions, original_references=None):
        return f"ToDate({ref_expressions[0]})"

    def tricc_operation_cast_string(self, ref_expressions, original_references=None):
        return f"ToString({ref_expressions[0]})"

    def tricc_operation_cast_boolean(self, ref_expressions, original_references=None):
        return f"ToBoolean({ref_expressions[0]})"

    def tricc_operation_datetime_to_decimal(self, ref_expressions, original_references=None):
        return f"ToDecimal({ref_expressions[0]})"

    # ============================================================
    # STRING OPERATORS
    # ============================================================
    def tricc_operation_concatenate(self, ref_expressions, original_references=None):
        return " + ".join(ref_expressions)

    def tricc_operation_length(self, ref_expressions, original_references=None):
        return f"Length({ref_expressions[0]})"

    def tricc_operation_diagnosis_list(self, ref_expressions, original_references=None):
        # Return as-is (string list)
        return ref_expressions[0] if ref_expressions else "''"

    # ============================================================
    # DATE / TIME OPERATORS
    # ============================================================
    def tricc_operation_today(self, ref_expressions, original_references=None):
        return "Today()"

    def tricc_operation_now(self, ref_expressions, original_references=None):
        return "Now()"

    def tricc_operation_age_day(self, ref_expressions, original_references=None):
        return f"AgeInDays({ref_expressions[0]})"

    def tricc_operation_age_month(self, ref_expressions, original_references=None):
        return f"AgeInMonths({ref_expressions[0]})"

    def tricc_operation_age_year(self, ref_expressions, original_references=None):
        return f"AgeInYears({ref_expressions[0]})"

    def tricc_operation_format_date(self, ref_expressions, original_references=None):
        # ref[0] = date, ref[1] = format string (optional)
        if len(ref_expressions) > 1:
            return f"ToString({ref_expressions[0]}, {ref_expressions[1]})"
        return f"ToString({ref_expressions[0]})"

    # ============================================================
    # CONDITIONAL / FLOW CONTROL
    # ============================================================
    def tricc_operation_if(self, ref_expressions, original_references=None):
        # if cond then true_val else false_val
        if len(ref_expressions) >= 3:
            return f"if {ref_expressions[0]} then {ref_expressions[1]} else {ref_expressions[2]}"
        return ref_expressions[0]

    def tricc_operation_ifs(self, ref_expressions, original_references=None):
        # Build nested if-then-else chain
        # ref_expressions layout: [cond1, res1, cond2, res2, ..., default]
        if len(ref_expressions) < 2:
            return ref_expressions[0] if ref_expressions else "null"
        parts = []
        i = 0
        while i < len(ref_expressions) - 1:
            cond = ref_expressions[i]
            res = ref_expressions[i + 1]
            parts.append(f"if {cond} then {res}")
            i += 2
        if i < len(ref_expressions):
            parts.append(f"else {ref_expressions[-1]}")
        return " ".join(parts)

    def tricc_operation_case(self, ref_expressions, original_references=None):
        # Similar to IFS but value-based matching
        # Layout: [value, (match1, res1), (match2, res2), ..., default]
        if len(ref_expressions) < 3:
            return ref_expressions[0] if ref_expressions else "null"
        value = ref_expressions[0]
        parts = []
        i = 1
        while i < len(ref_expressions) - 1:
            match_val = ref_expressions[i]
            res = ref_expressions[i + 1]
            parts.append(f"when {match_val} then {res}")
            i += 2
        if i < len(ref_expressions):
            parts.append(f"else {ref_expressions[-1]}")
        return f"case {value} {' '.join(parts)} end"

    def tricc_operation_coalesce(self, ref_expressions, original_references=None):
        # CQL coalesce
        items = ", ".join(ref_expressions)
        return f"Coalesce({items})"

    def tricc_operation_parenthesis(self, ref_expressions, original_references=None):
        # Simple wrapper
        return f"({ref_expressions[0]})" if ref_expressions else "()"

    # ============================================================
    # CDSS-SPECIFIC (NOT IMPLEMENTED)
    # ============================================================
    def tricc_operation_zscore(self, ref_expressions, original_references=None):
        raise NotImplementedError("ZSCORE is not supported yet")

    def tricc_operation_izscore(self, ref_expressions, original_references=None):
        raise NotImplementedError("IZSCORE is not supported yet")

    def tricc_operation_drug_dosage(self, ref_expressions, original_references=None):
        raise NotImplementedError("DRUG_DOSAGE is not supported yet")

    # ============================================================
    # ADDITIONAL / FALLBACK
    # ============================================================
    def tricc_operation_native(self, ref_expressions, original_references=None):
        # Raw expression passthrough
        return ref_expressions[0] if ref_expressions else ""

    def tricc_operation_add_or(self, ref_expressions, original_references=None):
        # left AND (right1 OR right2 OR ...)
        if len(ref_expressions) <= 1:
            return ref_expressions[0] if ref_expressions else ""
        left = ref_expressions[0]
        rights = " or ".join(ref_expressions[1:])
        return f"({left} and ({rights}))"

    # ============================================================
    # FHIRPath variants – delegate to CQL handlers.
    # ============================================================
    def tricc_operation_fhirpath_equal(self, ref_expressions, original_references=None):
        # Operands are already scalar-wrapped; just build the comparison.
        r_expr =  self.tricc_operation_equal(ref_expressions)
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_not_equal(self, ref_expressions, original_references=None):
        # Operands are already scalar-wrapped; just build the comparison.
        r_expr =  self.tricc_operation_not_equal(ref_expressions)
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_less_or_equal(self, ref_expressions, original_references=None):
        # Operands are already scalar-wrapped; just build the comparison.
        r_expr =  self.tricc_operation_less_or_equal(ref_expressions)
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_more_or_equal(self, ref_expressions, original_references=None):
        # Operands are already scalar-wrapped; just build the comparison.
        r_expr = self.tricc_operation_more_or_equal(ref_expressions)
        return self._wrap_operand_if_needed(r_expr, original_references)


    def tricc_operation_fhirpath_istrue(self, ref_expressions, original_references=None):
        # FHIRPath has no "is true" — CQL's tricc_operation_istrue() is not reused here.
        r_expr = f"({ref_expressions[0]} = true)"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_isnottrue(self, ref_expressions, original_references=None):
        r_expr = f"({ref_expressions[0]} != true)"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_isfalse(self, ref_expressions, original_references=None):
        r_expr = f"({ref_expressions[0]} = false)"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_isnotfalse(self, ref_expressions, original_references=None):
        r_expr = f"({ref_expressions[0]} != false)"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_isnull(self, ref_expressions, original_references=None):
        # FHIRPath has no "is null"; test the answer collection directly —
        # do not scalar-wrap to .value, we want existence of the collection itself.
        return f"{ref_expressions[0]}.empty()"

    def tricc_operation_fhirpath_isnotnull(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.exists()"

    def tricc_operation_fhirpath_selected(self, ref_expressions, original_references=None):
        select_ref = original_references[0] if original_references else None
        if self._is_boolean_item_reference(select_ref):
            return (
                f"({ref_expressions[0]}.where($this.exists()).value = {ref_expressions[1]})"
            )
        return self._choice_membership_expr(ref_expressions[0], ref_expressions[1])

    def tricc_operation_fhirpath_between(self, ref_expressions, original_references=None):
        # FHIRPath has no "between ... and ..."; expand to a range comparison.
        value, low, high = ref_expressions[0], ref_expressions[1], ref_expressions[2]
        r_expr = f"({value} >= {low} and {value} <= {high})"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_contains(self, ref_expressions, original_references=None):
        left_ref = original_references[0] if original_references else None
        if self._is_string_item_reference(left_ref):
            return f"({ref_expressions[0]}.where($this.exists()).value contains {ref_expressions[1]})"
        return self._choice_membership_expr(ref_expressions[0], ref_expressions[1])

    def tricc_operation_fhirpath_exists(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.exists()"

    def tricc_operation_fhirpath_notexists(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.empty()"

    def tricc_operation_fhirpath_coalesce(self, ref_expressions, original_references=None):
        joined = "|".join(ref_expressions) if ref_expressions else ""
        return f"({joined}).where($this.exists()).first()"

    def tricc_operation_fhirpath_if(self, ref_expressions, original_references=None):
        # FHIRPath has no "if ... then ... else ..."; use the iif() function.
        if len(ref_expressions) >= 3:
            r_expr = f"iif({ref_expressions[0]}, {ref_expressions[1]}, {ref_expressions[2]})"
        else:
            r_expr = ref_expressions[0]
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_ifs(self, ref_expressions, original_references=None):
        # IFS/CASE not supported in FHIRPath 2.0 – raise explicit error
        raise NotImplementedError("IFS is not supported by FHIRPath 2.0 – use CQL instead")

    def tricc_operation_fhirpath_case(self, ref_expressions, original_references=None):
        raise NotImplementedError("CASE is not supported by FHIRPath 2.0 – use CQL instead")

    def tricc_operation_fhirpath_zscore(self, ref_expressions, original_references=None):
        raise NotImplementedError("ZSCORE is not supported by FHIRPath 2.0")

    def tricc_operation_fhirpath_izscore(self, ref_expressions, original_references=None):
        raise NotImplementedError("IZSCORE is not supported by FHIRPath 2.0")

    def tricc_operation_fhirpath_drug_dosage(self, ref_expressions, original_references=None):
        raise NotImplementedError("DRUG_DOSAGE is not supported by FHIRPath 2.0")

    def tricc_operation_fhirpath_has_qualifier(self, ref_expressions, original_references=None):
        raise NotImplementedError("HAS_QUALIFIER is not supported by FHIRPath 2.0")

    def tricc_operation_fhirpath_count(self, ref_expressions, original_references=None):
        if len(ref_expressions)>1:
            items = ", ".join(ref_expressions)
            return f"{{{items}}}.count()"
        else:
            return f"{ref_expressions[0]}.count()"

    # ============================================================
    # ARITHMETIC / STRING / DATE — FHIRPath uses suffix functions
    # (X.round(), X.length()) rather than CQL's prefix Round(X)/Length(X),
    # and lowercase no-arg today()/now() rather than CQL's Today()/Now().
    # ============================================================
    def tricc_operation_fhirpath_round(self, ref_expressions, original_references=None):
        r_expr = f"{ref_expressions[0]}.round()"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_abs(self, ref_expressions, original_references=None):
        r_expr = f"{ref_expressions[0]}.abs()"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_length(self, ref_expressions, original_references=None):
        r_expr = f"{ref_expressions[0]}.length()"
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_concatenate(self, ref_expressions, original_references=None):
        # FHIRPath string concatenation uses "&" ("+" is arithmetic-only).
        r_expr = " & ".join(ref_expressions)
        return self._wrap_operand_if_needed(r_expr, original_references)

    def tricc_operation_fhirpath_today(self, ref_expressions, original_references=None):
        return "today()"

    def tricc_operation_fhirpath_now(self, ref_expressions, original_references=None):
        return "now()"

    # ============================================================
    # No clean FHIRPath equivalent — fail loudly rather than emit
    # CQL syntax (Min({...}), AgeInYears(x), ToString(x, fmt)) into an
    # extension declared as text/fhirpath.
    # ============================================================
    def tricc_operation_fhirpath_min(self, ref_expressions, original_references=None):
        raise NotImplementedError("MIN is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_max(self, ref_expressions, original_references=None):
        raise NotImplementedError("MAX is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_sum(self, ref_expressions, original_references=None):
        raise NotImplementedError("SUM is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_age_day(self, ref_expressions, original_references=None):
        raise NotImplementedError("AGE_DAY is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_age_month(self, ref_expressions, original_references=None):
        raise NotImplementedError("AGE_MONTH is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_age_year(self, ref_expressions, original_references=None):
        raise NotImplementedError("AGE_YEAR is not supported by FHIRPath 2.0 — use CQL instead")

    def tricc_operation_fhirpath_format_date(self, ref_expressions, original_references=None):
        raise NotImplementedError("FORMAT_DATE is not supported by FHIRPath 2.0 — use CQL instead")

    # ============================================================
    # CASTING & CONVERSION
    # ============================================================
    def tricc_operation_fhirpath_cast_number(self, ref_expressions, original_references=None):
        src = original_references[0] if original_references else None
        if self._operation_returns_boolean(src):
            return f"iif({ref_expressions[0]}, 1, 0)"
        return f"{ref_expressions[0]}.toDecimal()"

    def tricc_operation_fhirpath_cast_integer(self, ref_expressions, original_references=None):
        src = original_references[0] if original_references else None
        if self._operation_returns_boolean(src):
            return f"iif({ref_expressions[0]}, 1, 0)"
        return f"{ref_expressions[0]}.toInteger()"

    def tricc_operation_fhirpath_cast_date(self, ref_expressions, original_references=None):
        return f"({ref_expressions[0]}.toDate())"

    def tricc_operation_fhirpath_cast_string(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.toString()"

    def tricc_operation_fhirpath_cast_boolean(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.toBoolean()"

    def tricc_operation_fhirpath_datetime_to_decimal(self, ref_expressions, original_references=None):
        return f"{ref_expressions[0]}.toDecimal()"
    # For any other fhirpath_* not explicitly defined above, the fallback in
    # get_tricc_operation_expression_fhirpath will call the CQL handler directly.
    # Per-operand .first() wrapping has already been applied before reaching here.

    # ---------------------------------------------------------------------------
    # Validation (implements the abstract method from BaseOutPutStrategy)
    # ---------------------------------------------------------------------------

    def validate(self):
        """Basic structural validation of the generated FHIR resources.

        Logs counts and emits warnings when the export is obviously incomplete
        (the current state of the FHIRStrategy implementation).
        """
        q_count = len(self.questionnaires)
        cql_count = len(self.cql_libraries)
        fml_count = len(self.fml_mappings)
        lib_count = len(getattr(self, "cql_defines", {}))

        logger.info(
            f"FHIRStrategy validate: questionnaires={q_count}, "
            f"cql_libraries={cql_count}, fml_mappings={fml_count}, "
            f"cql_defines={lib_count}"
        )

        if q_count == 0:
            logger.warning("FHIRStrategy: No questionnaires were generated")
        if cql_count == 0 and not self.cql_defines:
            logger.warning(
                "FHIRStrategy: No CQL libraries generated (calculate / complex "
                "relevance logic not yet implemented in this strategy)"
            )
        if fml_count == 0:
            logger.warning("FHIRStrategy: No FML/StructureMap mappings generated")

        leftover = 0
        for q in (self.questionnaires or {}).values():
            leftover += strip_illegal_initials(q.get("item"))
        if leftover:
            logger.error(
                "FHIRStrategy: %s group/display item(s) still had illegal "
                "initial/initialExpression after sanitizer (SDC + openSRP $populate)",
                leftover,
            )

        # Future: add deeper checks (linkId uniqueness, expression syntax, etc.)
        logger.info("FHIRStrategy: basic validation complete")
