name: 'TRICC Action'
description: 'Run TRICC operations'
inputs:
  input_path:
    description: 'Input path for TRICC'
    required: true
  output_path:
    description: 'output path for TRICC'
    required: true
  output_strategy:
    description: 'Output strategy for TRICC'
    required: true
  input_strategy:
    description: 'Input strategy for TRICC'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install tricc-oo
      run: |
        pip install tricc-oo
      shell: bash

    - name: Run TRICC
      run: |
        mkdir -p ./${{ inputs.output_path }}
        python -c "
        from tricc_oo.strategies.input.drawio import DrawioStrategy
        from tricc_oo.strategies.output.xls_form import XLSFormStrategy
        from tricc_oo.strategies.output.xlsform_cdss import XLSFormCDSSStrategy
        from tricc_oo.strategies.output.xlsform_cht import XLSFormCHTStrategy
        from tricc_oo.models.lang import SingletonLangClass
        import os
        import logging
        class ColorFormatter(logging.Formatter):
            # Define ANSI escape codes for colors
            grey = '\x1b[38;21m'
            yellow = '\x1b[33;21m'
            red = '\x1b[31;21m'
            bold_red = '\x1b[31;1m'
            reset = '\x1b[0m'
            format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)'

            # Map log levels to their respective colors
            FORMATS = {
                logging.DEBUG: grey + format + reset,
                logging.INFO: grey + format + reset,
                logging.WARNING: yellow + format + reset,
                logging.ERROR: red + format + reset,
                logging.CRITICAL: bold_red + format + reset,
            }

            def format(self, record):
                # Get the appropriate color format for the log level
                log_fmt = self.FORMATS.get(record.levelno)
                formatter = logging.Formatter(log_fmt)
                return formatter.format(record)




        handler = logging.StreamHandler()
        handler.setFormatter(ColorFormatter())
        logger = logging.getLogger('default')
        logger.addHandler(handler)
        langs = SingletonLangClass()
        in_filepath = '${{ inputs.input_path }}'
        file_content = []
        files = []
        in_filepath_list = in_filepath.split(',')
        for in_filepath in in_filepath_list:
            pre, ext = os.path.splitext(in_filepath)
            if os.path.isdir(in_filepath):
                files = [
                    os.path.join(in_filepath, f)
                    for f in os.listdir(in_filepath) 
                    if f.endswith('.drawio')
                ]
            elif os.path.isfile(in_filepath) and in_filepath.endswith('.drawio'):
                files = [in_filepath]
                
            for f in files:
                with open(f, 'r') as s:
                    content = s.read()
                    file_content.append(content)
        if not file_content:
            logger.critical(f'{in_filepath} is neither a drawio file nor a directory containing drawio files')
            exit(-1)
        input_strategy = ${{ inputs.input_strategy }}(file_content)
        media_path = os.path.join('${{ inputs.output_path }}', 'media-tmp')
        project = input_strategy.execute(file_content, media_path)
        output_strategy = ${{ inputs.output_strategy }}(project, './${{ inputs.output_path }}')      
        output = output_strategy.execute()
        "
      shell: bash
